### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'

### ISSUE THREAD

**Issue by KingBarker** [useragents/Zefoy-TikTok-Automator#27]
chrome driver path is set, asked to input captcha then receive this error 

Traceback (most recent call last):
  File "C:\Users\usr\OneDrive\Desktop\Zefoy-TikTok-Automator-main\tiktok.py", line 276, in <module>
    obj.main()
  File "C:\Users\usr\OneDrive\Desktop\Zefoy-TikTok-Automator-main\tiktok.py", line 226, in main
    self.check_status()
  File "C:\Users\usr\OneDrive\Desktop\Zefoy-TikTok-Automator-main\tiktok.py", line 55, in check_status
    element = self.driver.find_element_by_xpath(value)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'

C:\Users\usr\OneDrive\Desktop\Zefoy-TikTok-Automator-main>

**Comment by useragents** [comment]
Code must've been edited, or selenium updated attributes that I'm not aware of. Either way, download latest version and install the requirements from `requirements.txt`

Ensure you are using the same selenium version.
