### ISSUE TITLE
OSError, and don't know why

### ISSUE THREAD

**Issue by Impre-visible** [useragents/Zefoy-TikTok-Automator#53]
Hi, when I want to boost likes I have this error :
```py
Traceback (most recent call last):
  File "C:\Users\Manafix\Desktop\Zefoy-TikTok-Automator-main\tiktok.py", line 174, in <module>
    obj.main()
  File "C:\Users\Manafix\Desktop\Zefoy-TikTok-Automator-main\tiktok.py", line 88, in main
    self.send_bot(search_box, video_url_box, vid_info, div)
  File "C:\Users\Manafix\Desktop\Zefoy-TikTok-Automator-main\tiktok.py", line 110, in send_bot
    self.driver.find_element('xpath', send_button).click()
  File "C:\Users\Manafix\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Manafix\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manafix\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Manafix\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=108.0.5359.99)
Stacktrace:
Backtrace:
        (No symbol) [0x0023F243]
        (No symbol) [0x001C7FD1]
        (No symbol) [0x000BCF10]
        (No symbol) [0x000ED003]
        (No symbol) [0x000E32A6]
        (No symbol) [0x0010858C]
        (No symbol) [0x000E2BFF]
        (No symbol) [0x00108804]
        (No symbol) [0x0011C9EB]
        (No symbol) [0x00108386]
        (No symbol) [0x000E163C]
        (No symbol) [0x000E269D]
        GetHandleVerifier [0x004D9A22+2655074]
        GetHandleVerifier [0x004CCA24+2601828]
        GetHandleVerifier [0x002E8C0A+619850]
        GetHandleVerifier [0x002E7830+614768]
        (No symbol) [0x001D05FC]
        (No symbol) [0x001D5968]
        (No symbol) [0x001D5A55]
        (No symbol) [0x001E051B]
        BaseThreadInitThunk [0x7692FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x77C47BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77C47B8E+238]
        (No symbol) [0x00000000]

Exception ignored in: <function Chrome.__del__ at 0x00000226AEC09440>
Traceback (most recent call last):
  File "C:\Users\Manafix\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
  File "C:\Users\Manafix\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
OSError: [WinError 6] Descripteur non valide
```

**Comment by useragents** [comment]
You read that it says LIKES are OFFLINE and you continue to select that option and expect it to work? 🤦‍♂️🤦‍♂️

**Comment by 7elmie** [comment]
it says _LIKES_ are _OFFLINE_ and you continue to select that option and expect it 
Your way of writing the code needs references and continuous improvement in order to avoid the appearance of such errors  It is also possible to use tools to review your code
