### ISSUE TITLE
 self.driver = uc.Chrome()

### ISSUE THREAD

**Issue by killerghost-92** [useragents/Zefoy-TikTok-Automator#58]
C:\Users\hp\AppData\Local\Programs\Python\Python311\Scripts\Zefoy-TikTok-Automator-main>py tiktok.py
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Scripts\Zefoy-TikTok-Automator-main\tiktok.py", line 176, in <module>
    obj = zefoy()
          ^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Scripts\Zefoy-TikTok-Automator-main\tiktok.py", line 24, in __init__
    self.driver = uc.Chrome()
                  ^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 409, in __init__
    browser = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1433, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType

C:\Users\hp\AppData\Local\Programs\Python\Python311\Scripts\Zefoy-TikTok-Automator-main>

**Comment by useragents** [comment]
Is google chrome installed?

**Comment by killerghost-92** [comment]
yes

**Comment by Aariz01** [comment]
did you ever fix this problem im trying to download this to but im stuck because on youtube they have you edit the program but the code is different so im trying to figure out where to insert the code , if you even have to. 
Let me know

**Comment by useragents** [comment]
@Aariz01 You do not need to edit the Python script at all. Follow the usage in the github readme file.

**Comment by Aariz01** [comment]
@useragents I loaded everything and its still giving me the same error. Im on the last part where you put in tiktok.py an it says tiktok.py is not recognized as internal or external command. Im right there let me know some agent.
