### ISSUE TITLE
how i slove this problem

### ISSUE THREAD

**Issue by anhtahaylove** [useragents/Zefoy-TikTok-Automator#78]
how i slove this problem

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Tiktok\Zefoy-TikTok-Automator-main\tiktok.py", line 182, in <module>
    obj.main()
  File "C:\Users\Administrator\Desktop\Tiktok\Zefoy-TikTok-Automator-main\tiktok.py", line 96, in main
    self.send_bot(search_box, video_url_box, vid_info, div)
  File "C:\Users\Administrator\Desktop\Tiktok\Zefoy-TikTok-Automator-main\tiktok.py", line 105, in send_bot
    element = self.driver.find_element('xpath', main_xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div[5]/div/form/div/input"}
  (Session info: chrome=111.0.5563.65)
Stacktrace:
Backtrace:
        (No symbol) [0x0105DCE3]
        (No symbol) [0x00FF39D1]
        (No symbol) [0x00F04DA8]
        (No symbol) [0x00F3019F]
        (No symbol) [0x00F303AB]
        (No symbol) [0x00F5EE62]
        (No symbol) [0x00F4AF14]
        (No symbol) [0x00F5D57C]
        (No symbol) [0x00F4ACC6]
        (No symbol) [0x00F26F68]
        (No symbol) [0x00F280CD]
        GetHandleVerifier [0x012D3832+2506274]
        GetHandleVerifier [0x01309794+2727300]
        GetHandleVerifier [0x0130E36C+2746716]
        GetHandleVerifier [0x01106690+617600]
        (No symbol) [0x00FFC712]
        (No symbol) [0x01001FF8]
        (No symbol) [0x010020DB]
        (No symbol) [0x0100C63B]
        BaseThreadInitThunk [0x754A7D69+25]
        RtlInitializeExceptionChain [0x770AB74B+107]
        RtlClearBits [0x770AB6CF+191]

**Comment by KneesDev** [comment]
You need the Chrome Driver
